title: copy run start
description: Saving network insights before the next reload.
url: https://karsagar28.github.io
baseurl: ""
lang: en-US
timezone: America/New_York
author: karsagar28

permalink: /notes/:title/

plugins:
  - jekyll-feed
  - jekyll-seo-tag

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
